Repository wecode-bootcamp-korea/fullstack2-2nd-Linked-IT-frontend, pull requests merged in 2021-11, with the labels that each got.

#48 [한승완] [나의 인맥] 화면 레이아웃 개발
  package.json
  public/images/ico_addressbook.svg
  public/images/ico_briefcase.svg
  public/images/ico_briefcase2.svg
  public/images/ico_building.svg
  public/images/ico_calendar.svg
  public/images/ico_close.svg
  public/images/ico_hashtag.svg
  public/images/ico_newsletter.svg
  public/images/ico_people.svg
  public/images/ico_speech_bubble.svg
  src/Routes.js
  src/components/CompanyProfileCard/CompanyProfileCard.js
  src/pages/Jobs/JobPostingDetail.js
  src/pages/MyNetwork/MyNetwork.js
  src/pages/MyNetwork/components/Layer.js
  src/pages/MyNetwork/components/Loader.js
  src/pages/MyNetwork/components/Menus.js
  src/pages/MyNetwork/components/StyledBody.js
  src/pages/MyNetwork/components/StyledHeader.js
  src/pages/MyNetwork/components/StyledSection.js
  src/pages/MyNetwork/data/InvitationsData.js
  src/pages/MyNetwork/data/MyProfileData.js
Labels: Status: 리뷰 요청

#49 [한지훈] [Feed] Post카드 구현 중
  .vscode/settings.json
  package-lock.json
  src/components/FloatingFooter/FloatingFooter.js
  src/pages/Feed/Feed.js
  src/pages/Feed/FeedProfile.js
  src/pages/Feed/LikeBtnAndModal.js
  src/pages/Feed/Post.js
  src/pages/Feed/PostContent.js
  src/pages/Feed/PostProfile.js
  src/pages/Feed/PostReply.js
  src/pages/Feed/PostSocialInteract.js
  src/pages/Feed/data/Images/reply.svg
  src/pages/Feed/data/Images/send.svg
  src/pages/Feed/data/Images/share.svg
  src/pages/Feed/data/Images/socialIcons.js
  src/pages/Feed/data/Images/thumbDefault.svg
  src/pages/Feed/data/MyProfileData.js
  src/pages/Feed/data/PostData.js
  src/pages/Feed/data/Profile.js
  src/styles/theme.js
  src/utils/LanguageUtil.js
Labels: Status: 리뷰 요청

#56 [한승완] [나의 인맥] 개인 프로필 카드 레이아웃 개발
  public/images/profile_default.png
  src/pages/MyNetwork/components/Layer.js
  src/pages/MyNetwork/components/ProfileCard.js
  src/pages/MyNetwork/components/StyledBody.js
Labels: Status: 리뷰 요청

#53 [한지훈] [Feed] Post 쓰기, 수정, 삭제 구현
  public/images/ico_articleColored.svg
  public/images/ico_badge.svg
  public/images/ico_bars.svg
  public/images/ico_document.svg
  public/images/ico_etc.svg
  public/images/ico_eventColored.svg
  public/images/ico_image.svg
  public/images/ico_imageColored.svg
  public/images/ico_reply.svg
  public/images/ico_send.svg
  public/images/ico_share.svg
  public/images/ico_tallShort.svg
  public/images/ico_textBox.svg
  public/images/ico_thinClose.svg
  public/images/ico_thumb.svg
  public/images/ico_video.svg
  public/images/ico_videoColored.svg
  src/components/FloatingFooter/FloatingFooter.js
  src/pages/Feed/Feed.js
  src/pages/Feed/FeedProfile.js
  src/pages/Feed/LikeBtnAndModal.js
  src/pages/Feed/Post.js
  src/pages/Feed/PostContent.js
  src/pages/Feed/PostProfile.js
  src/pages/Feed/PostReply.js
  src/pages/Feed/PostReplyList.js
  src/pages/Feed/PostSocialInteract.js
  src/pages/Feed/WritePost.js
  src/pages/Feed/data/MyProfileData.js
  src/pages/Feed/data/PostData.js
  src/pages/Feed/data/UploadBtns.js
  src/pages/Feed/data/modalUploadBtns.js
  src/utils/LanguageUtil.js
Labels: Status: 추가 기능 구현중, Status: 리뷰 반영 중

#61 [한승완] Not Found 페이지 개발
  src/Routes.js
  src/pages/Connections/Connections.js
  src/pages/Jobs/JobPostingDetail.js
  src/pages/Jobs/Jobs.js
  src/pages/MyNetwork/components/CardListContainer.js
  src/pages/MyNetwork/components/Layer.js
  src/pages/NotFound/NotFound.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#35 [김시원] [Profile] 프로필 메인 카드
  public/data/profile/careerData.json
  public/data/profile/educationData.json
  public/data/profile/profileData.json
  public/data/profile/profileDataUrl.json
  public/images/defaultProfile.png
  public/images/defaultProfileBg.png
  src/components/UserCard/UserCard.js
  src/index.js
  src/pages/Profile/Profile.js
  src/pages/Profile/ProfileMain/Carousel/Card.js
  src/pages/Profile/ProfileMain/Carousel/Carousel.js
  src/pages/Profile/ProfileMain/Detail.js
  src/pages/Profile/ProfileMain/DropDown/InterestDropDown.js
  src/pages/Profile/ProfileMain/DropDown/MoresDropDown.js
  src/pages/Profile/ProfileMain/DropDown/sectionsDropDown.js
  src/pages/Profile/ProfileMain/Informaion/Information.js
  src/pages/Profile/ProfileMain/ProfileBackGround.js
  src/pages/Profile/ProfileMain/ProfileImage.js
  src/pages/Profile/ProfileMain/ProfileMain.js
  src/pages/Profile/data/dropDownData.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#65 Refactor: 회원가입/로그인 페이지의 validateInput 함수를 컴포넌트 밖으로 분리 등
  src/Routes.js
  src/components/GlobalFooter/GlobalFooter.js
  src/pages/SignIn/SignIn.js
  src/pages/SignUp/SignUp.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#63 [한승완] [나의 인맥] API 호출 구조로 변경
  public/data/mynetwork/myProfileData.json
  src/Routes.js
  src/pages/Connections/Connections.js
  src/pages/MyNetwork/MyNetwork.js
  src/pages/MyNetwork/components/Layer.js
  src/pages/MyNetwork/components/Menus.js
  src/pages/MyNetwork/components/ProfileCard.js
Labels: Status: 리뷰 요청

#68 [이성재] [검색] 메인 검색 페이지 구현
  public/data/peopleData.json
  src/Routes.js
  src/components/Button/Button.js
  src/components/CompanyProfileCard/CompanyProfileCard.js
  src/components/JobPostingCard/JobPostingCard.js
  src/components/TopNav/NavLinkData.js
  src/components/TopNav/SearchDropDown/SearchDropDown.js
  src/components/TopNav/TopNav.js
  src/pages/Jobs/JobPostingDetail.js
  src/pages/MainSearch/MainSearch.js
  src/pages/MyNetwork/MyNetwork.js
  src/pages/MyNetwork/components/CardListContainer.js
  src/pages/PeopleSearch/PeopleSearch.js
  src/pages/Search/Search.js
  src/styles/theme.js
  src/utils/SearchUtil.js
Labels: Status: 리뷰 요청

#70 [김시원] [Profile] 아는 사람 찾기 컴포넌트 구현
  public/data/profile/mayKnowListData.json
  public/data/profile/profileData.json
  public/data/profile/profileDataUrl.json
  src/components/UserCard/UserCard.js
  src/pages/Profile/Carousel/Card.js
  src/pages/Profile/Carousel/Carousel.js
  src/pages/Profile/DropDown/InterestDropDown.js
  src/pages/Profile/DropDown/MoresDropDown.js
  src/pages/Profile/DropDown/sectionsDropDown.js
  src/pages/Profile/Informaion/CareerCard.js
  src/pages/Profile/Informaion/EducationCard.js
  src/pages/Profile/Informaion/Information.js
  src/pages/Profile/MayKnowList.js
  src/pages/Profile/Modals/BasicEditModal.js
  src/pages/Profile/Modals/CareerAddModal.js
  src/pages/Profile/Modals/CareerEditModal.js
  src/pages/Profile/Modals/EducationAddModal.js
  src/pages/Profile/Modals/EducationEditModal.js
  src/pages/Profile/Modals/PopUpMessage.js
  src/pages/Profile/Modals/components/AskCancelModal.js
  src/pages/Profile/Modals/components/CheckBox.js
  src/pages/Profile/Modals/components/EndInput.js
  src/pages/Profile/Modals/components/StartInput.js
  src/pages/Profile/Modals/components/TextArea.js
  src/pages/Profile/Modals/components/TextInput.js
  src/pages/Profile/Profile.js
  src/pages/Profile/ProfileMain/ProfileMain.js
Labels: Status: 리뷰 요청

#64 [한승완] [채용공고] API 호출 구조로 변경
  public/data/jobs/JobPostingDetailData1.json
  public/data/jobs/JobPostingDetailData2.json
  public/data/jobs/JobPostingDetailData3.json
  public/data/jobs/JobPostingDetailData4.json
  public/data/jobs/JobPostingDetailData5.json
  public/data/jobs/JobPostingListData020.json
  public/data/jobs/JobPostingListData2020.json
  src/components/CompanyProfileCard/CompanyProfileCard.js
  src/components/JobPostingCard/JobPostingCard.js
  src/components/JobPostingCard/data/JobPostingData.js
  src/pages/Jobs/JobPostingDetail.js
  src/pages/Jobs/Jobs.js
  src/pages/Jobs/data/JobPostingDetailData.js
  src/pages/MainSearch/MainSearch.js
Labels: Status: Accepted

#73 [김시원] [Profile] 배경사진, 프로필사진 업로드 모달 구현
  public/images/imgUploadDefault.png
  src/pages/Profile/DropDown/InterestDropDown.js
  src/pages/Profile/DropDown/MoresDropDown.js
  src/pages/Profile/DropDown/sectionsDropDown.js
  src/pages/Profile/ImgUploadModal.js
  src/pages/Profile/MayKnowList.js
  src/pages/Profile/Profile.js
  src/pages/Profile/ProfileMain/ProfileBackGround.js
  src/pages/Profile/ProfileMain/ProfileImage.js
  src/pages/Profile/ProfileMain/ProfileMain.js
Labels: Status: 리뷰 요청

#72 [한승완] [나의 인맥] 1촌 맺기 끊기 기능 개발
  public/data/mynetwork/myProfileData.json
  public/data/mynetwork/userCardListData.json
  src/Routes.js
  src/components/CompanyProfileCard/CompanyProfileCard.js
  src/components/JobPostingCard/JobPostingCard.js
  src/pages/Connections/Connections.js
  src/pages/Connections/FriendList.js
  src/pages/Connections/utils/TempAPI.js
  src/pages/Connections/utils/TempUtil.js
  src/pages/Jobs/JobPostingDetail.js
  src/pages/Jobs/Jobs.js
  src/pages/MyNetwork/MyNetwork.js
  src/pages/MyNetwork/components/CardListContainer.js
  src/pages/MyNetwork/components/Layer.js
  src/pages/MyNetwork/components/ProfileCard.js
  src/pages/MyNetwork/components/StyledSection.js
  src/pages/MyNetwork/data/InvitationsData.js
  src/pages/MyNetwork/data/MyProfileData.js
  src/pages/NotFound/NotFound.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#74 [한지훈] [Feed] API 연결
  src/pages/Feed/Feed.js
  src/pages/Feed/FeedProfile.js
  src/pages/Feed/LikeBtnAndModal.js
  src/pages/Feed/Post.js
  src/pages/Feed/PostContent.js
  src/pages/Feed/PostModal.js
  src/pages/Feed/PostProfile.js
  src/pages/Feed/PostReply.js
  src/pages/Feed/PostReplyList.js
  src/pages/Feed/PostSocialInteract.js
  src/pages/Feed/WritePost.js
  src/pages/Feed/data/MyProfileData.js
  src/pages/Feed/data/PostData.js
  src/pages/Feed/data/PostData2.js
Labels: Status: 리뷰 요청

#75 [이성재] [검색] 사람 검색 페이지 레이아웃 구현
  package-lock.json
  src/components/TopNav/SearchDropDown/SearchDropDown.js
  src/components/TopNav/TopNav.js
  src/pages/MainSearch/MainSearch.js
  src/pages/PeopleSearch/PeopleSearch.js
Labels: Status: 리뷰 요청

#77 [한승완] [공통] Not Found 페이지 사용을 위해 TopNav 라우팅 수정
  src/Routes.js
  src/pages/Connections/Connections.js
  src/pages/Feed/Feed.js
  src/pages/Jobs/Jobs.js
  src/pages/MainSearch/MainSearch.js
  src/pages/MyNetwork/MyNetwork.js
  src/pages/PeopleSearch/PeopleSearch.js
  src/pages/Profile/Profile.js
Labels: Status: 리뷰 요청

#79 [한승완] [나의 인맥] 검색 로직 수정
  public/data/mynetwork/myProfileData.json
  src/pages/Connections/utils/TempUtil.js
Labels: Status: 리뷰 요청

#84 [이성재] [검색] Pagination 구현
  src/components/TopNav/SearchDropDown/SearchDropDown.js
  src/components/TopNav/TopNav.js
  src/pages/MainSearch/MainSearch.js
  src/pages/PeopleSearch/PeopleSearch.js
Labels: Status: 리뷰 요청

#86 [한승완] [나의 인맥] 화면 확대 시에도 무한스크롤 동작하도록 수정
  src/pages/MyNetwork/components/Layer.js
Labels: Status: 리뷰 요청
